version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-platform-dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-platform-dependencies-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - eventuate-platform-dependencies-
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-platform-dependencies-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./.circleci/deploy-artifacts.sh
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - publish
